language: python
sudo: required
python:
    - "3.5"
install:
    - "sudo apt-get install python-enchant"
    - "pip install -r requirements.txt"

script: nosetests --with-coverage --cover-inclusive --cover-package=bslint

after_script:
    - cd bslint && pylint bslint
    - cd ../tests && pylint tests